# Generated by Django 4.2.1 on 2023-05-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_distr', '0002_delete_pedidos_clientes_creador_productos_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='creador',
        ),
    ]
